version: "3"
services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      CLICKHOUSE_DB: ariadne
      CLICKHOUSE_USER: ariadne
      CLICKHOUSE_PASSWORD: ariadne-pass
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  ui:
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - "9008:80"
    links:
      - "server:database"
    environment:
      CH_NAME: dev
      CH_HOST: localhost:8123
      CH_LOGIN: ariadne
      CH_PASSWORD: ariadne-pass